version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI
      - JWT_SECRET
    restart: unless-stopped
    volumes:
      - ./backend:/app

  medication-availability-finder:
    build:
      context: ./medication-availability-finder
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./medication-availability-finder:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
